assignment_profile:
  outputs:
    dev:
      dataset: chicago_taxi
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: astrafy-assignment
      threads: 1
      type: bigquery
  target: dev
